AWSTemplateFormatVersion: '2010-09-09' #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
Description: Create a role for us to assume and create a resource we have access too
Parameters:
  BucketName:
    Default: "sts-fun-vs1"
Resources: 
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: sts-fun-vs1
  StsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: s3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: [
                'arn:aws:s3:::sts-fun-vs1/*'
                'arn:aws:s3:::sts-fun-vs1',
                ]
