#!/usr/bin/env bash
echo "== create bucket"

#check if atleast one argument is provided
if [ -z "$1" ]; then
  echo "There needs to be a bucket name eg. ./bucket my-bucket-name"
  exit 1
fi
BUCKET_NAME=$1

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration LocationConstraint="ap-south-1" \
--query Location \
--output text