#!/usr/bin/env bash

#exit immediately if any command returns a non-zero status
set -e

#where wi'll store these files
OUTPUT_DIR="/tmp/s3-bash-scripts"

#remove folder if it already exists
rm -r $OUTPUT_DIR

#let's create output folder
mkdir -p $OUTPUT_DIR

#generate a random number
#to determine how many files to create
NUM_FILES=$((RANDOM % 6 + 5))

for ((i=1; i<=$NUM_FILES;i++));do
    #generate a random filename
    FILENAME="$OUTPUT_DIR/file_$i.txt"

    #generate random data and write it to the file
    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done

tree $OUTPUT_DIR