AWSTemplateFormatVersion: '2010-09-09' #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
Description: CNF S3 Bucket
Resources:
  S3Bucket: #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: DOC-EXAMPLE-BUCKET
      #we don't need to provide aws name as aws will generate a random name for us.